import "@/styles/globals.css";
import clsx from "clsx";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={clsx('bg-cover bg-no-repeat',
      'bg-[url("/assets/home/background-home-mobile.jpg")]',
      'md:bg-[url("/assets/home/background-home-tablet.jpg")]', 
      'xl:bg-[url("/assets/home/background-home-desktop.jpg")]')}>
      <body>
        <div>header</div>
        {children}
        </body>
    </html>
  )
}
